const URL = "https://stancosmin28.github.io/bransha";

const data = {
  branshaLogo: `${URL}/bransha-logo.svg`,
  tabletImg: `${URL}/munn-app.jpeg`,
  phoneImg: `${URL}/phone-img.webp`,
  munn: `${URL}/munn.svg`,
  iPhoneSVG: `${URL}/iphone_16.svg`,
  iPhoneSVGV: `${URL}/iphone_16_vertical.svg`,
  teamSVG: `${URL}/team.svg`,
  auroraBG: `${URL}/aurora_bg.gif`,
  munn3DV1: `${URL}/munn-3d-v1.png`,
  munn3DV2: `${URL}/munn-3d-v2.webp`,
  tabletV1: `${URL}/tablet-v1.webp`,
  tabletV2: `${URL}/tablet-v2.webp`,
  tabletV3: `${URL}/tablet-v3.webp`,
  munnApps: `${URL}/MUNN-apps.webp`,
  headerParticles: `${URL}/headerParticles.webp`,
  googlePlay: `${URL}/google_play.webp`,
  appStore: `${URL}/app_store.webp`,
  iconsSVG: {
    bransha: `${URL}/bransha-icon.svg`,
    analytics: `${URL}/analytics-icon.svg`,
    building: `${URL}/building-icon.svg`,
    munn: `${URL}/munn-icon.svg`,
    iluminatAutomatizat: `${URL}/iluminat-automatizat.svg`,
    analizaTimpReal: `${URL}/analiza-timp-real.svg`,
    controlAcces: `${URL}/control-acces.svg`,
    controlHVAC: `${URL}/control-HVAC.svg`,
    optimizareEnergetica: `${URL}/optimizare-energetica.svg`,
    securitateSupraveghere: `${URL}/securitate-supraveghere.svg`,
    sigurantaIncendiu: `${URL}/siguranta-incendiu.svg`,
    sigurantaInundatie: `${URL}/siguranta-inundatie.svg`,
  },
  munnIphone1: `${URL}/munn-iphone-img-1.png`,
  munnIphone2: `${URL}/munn-iphone-img-2.png`,
  munnIphone3: `${URL}/munn-iphone-img-3.png`,
  munnIphone4: `${URL}/munn-iphone-img-4.png`,
};

export default data;
